image: Visual Studio 2019
platform: x64
configuration: Release

environment:
  global:
    TOXENV: py-whl
    # PyPI username and encrypted password
    TWINE_USERNAME: anthrotype
    TWINE_PASSWORD:
      secure: 9zLozI+1vEqeYX/OmuDcow==

  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9.x"
      PYTHON_ARCH: "64"

# matrix:
#   fast_finish: true

install:
  # Fetch submodules
  - git submodule update --init --recursive

  # Prepend Python to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade pip, setuptools and wheel
  - "python -m pip install --upgrade pip"
  - "python -m pip install --upgrade setuptools wheel"

  # Install test requirements
  - "python -m pip install tox"

build: false

test_script:
  # run the project tests
  - tox

on_failure:
  # print environment variables
  - ps: dir "env:"
  # print content of tox log files
  - ps: get-content .tox\*\log\*

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report
  - path: dist\*.whl

# Deploy wheels on tags to PyPI
on_success:
  - ps: >-
      if($env:APPVEYOR_REPO_TAG -eq 'true') {
        Write-Output ("Deploying " + $env:APPVEYOR_REPO_TAG_NAME + " to PyPI...")
        pip install --upgrade twine
        twine upload dist\*.whl
      } else {
        Write-Output "Not deploying as this is not a tagged commit"
      }
